spring:
  application:
    name: UserAuthService
  datasource:
    url: jdbc:mysql://localhost:3306/userauthservice
    username: userauthservice_user
#    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true